{
 "title": "esp32s",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_temperature{mac=\"A8032AEA96D4\"}",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_temperature{mac=\"84CCA81236F0\"}",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_temperature{mac=\"A8032AEAA504\"}",
     "legendFormat": "Living"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "esp32_temperature{mac=\"A8032AEA96D4\"}",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_temperature{mac=\"84CCA81236F0\"}",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_temperature{mac=\"A8032AEAA504\"}",
     "legendFormat": "Living"
    },
    { "expr": "avg(esp32_temperature)", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_humidity{mac=\"A8032AEA96D4\"}",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_humidity{mac=\"84CCA81236F0\"}",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_humidity{mac=\"A8032AEAA504\"}",
     "legendFormat": "Living"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "esp32_humidity{mac=\"A8032AEA96D4\"}",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_humidity{mac=\"84CCA81236F0\"}",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_humidity{mac=\"A8032AEAA504\"}",
     "legendFormat": "Living"
    },
    { "expr": "avg(esp32_humidity)", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_pressure{mac=\"A8032AEA96D4\"}",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_pressure{mac=\"84CCA81236F0\"}",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_pressure{mac=\"A8032AEAA504\"}",
     "legendFormat": "Living"
    }
   ]
  },
  {
   "title": "pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "esp32_pressure{mac=\"A8032AEA96D4\"} > 800",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_pressure{mac=\"84CCA81236F0\"} > 800",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_pressure{mac=\"A8032AEAA504\"} > 800",
     "legendFormat": "Living"
    },
    { "expr": "avg(esp32_pressure > 800)", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_epoch{mac=\"A8032AEA96D4\"} * 1000",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_epoch{mac=\"84CCA81236F0\"} * 1000",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_epoch{mac=\"A8032AEAA504\"} * 1000",
     "legendFormat": "Living"
    }
   ]
  },
  {
   "title": "epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "esp32_epoch{mac=\"A8032AEA96D4\"} * 1000",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_epoch{mac=\"84CCA81236F0\"} * 1000",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_epoch{mac=\"A8032AEAA504\"} * 1000",
     "legendFormat": "Living"
    }
   ]
  },
  {
   "title": "Battery level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp32_bat_lvl{mac=\"A8032AEA96D4\"}",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_bat_lvl{mac=\"84CCA81236F0\"}",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_bat_lvl{mac=\"A8032AEAA504\"}",
     "legendFormat": "Living"
    }
   ]
  },
  {
   "title": "battery level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "esp32_bat_lvl{mac=\"A8032AEA96D4\"}",
     "legendFormat": "Bedroom"
    },
    {
     "expr": "esp32_bat_lvl{mac=\"84CCA81236F0\"}",
     "legendFormat": "Cave"
    },
    {
     "expr": "esp32_bat_lvl{mac=\"A8032AEAA504\"}",
     "legendFormat": "Living"
    }
   ]
  },
  {
   "title": "MAC mapping",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 40 },
   "options": {
    "content": "| MAC          | Room    |\n| ------------ | ------- |\n| A8032AEA96D4 | Bedroom |\n| 84CCA81236F0 | Cave    |\n| A8032AEAA504 | Living  |"
   }
  }
 ]
}